//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadScanner.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public int Id { get; set; }
        public int TripId { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public Nullable<double> AccelerationX { get; set; }
        public Nullable<double> AccelerationY { get; set; }
        public Nullable<double> AccelerationZ { get; set; }
        public Nullable<double> Speed { get; set; }
        public System.DateTime MeasurementTime { get; set; }
        public Nullable<double> AccelerationMagnitude { get; set; }
        public Nullable<double> SnappedLatitude { get; set; }
        public Nullable<double> SnappedLongitude { get; set; }
    
        public virtual Trip Trip { get; set; }
    }
}
