//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadScanner.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RoadScannerContext : DbContext
    {
        public RoadScannerContext()
            : base("name=RoadScannerContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ManualAnomaly> ManualAnomalies { get; set; }
        public virtual DbSet<Measurement> Measurements { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
    }
}
