//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadScanner.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentChain5
    {
        public Nullable<int> Segment1Id { get; set; }
        public Nullable<int> Segment2Id { get; set; }
        public Nullable<int> Segment3Id { get; set; }
        public Nullable<int> Segment4Id { get; set; }
        public Nullable<int> Segment5Id { get; set; }
        public Nullable<double> speedAvg1 { get; set; }
        public Nullable<double> speedVar1 { get; set; }
        public Nullable<double> speedAvg2 { get; set; }
        public Nullable<double> speedVar2 { get; set; }
        public Nullable<double> speedAvg3 { get; set; }
        public Nullable<double> speedVar3 { get; set; }
        public Nullable<double> speedAvg4 { get; set; }
        public Nullable<double> speedVar4 { get; set; }
        public Nullable<double> speedAvg5 { get; set; }
        public Nullable<double> speedVar5 { get; set; }
        public int ContainAnomaly { get; set; }
    }
}
