//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadScanner.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        public int Id { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> speedAvg { get; set; }
        public Nullable<double> speedVar { get; set; }
        public Nullable<int> NextSegmentId { get; set; }
        public Nullable<int> samplesCount { get; set; }
        public Nullable<double> AvgSpentTime { get; set; }
        public Nullable<double> VarSpentTime { get; set; }
        public Nullable<double> AccelerationMagnitude { get; set; }
    }
}
