//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadScanner.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segments_SegmentChain6_4AnomalySpreaded
    {
        public int Segment1Id { get; set; }
        public int Segment2Id { get; set; }
        public int Segment3Id { get; set; }
        public int Segment4Id { get; set; }
        public int Segment5Id { get; set; }
        public int Segment6Id { get; set; }
        public Nullable<double> speedAvg1 { get; set; }
        public Nullable<double> speedVar1 { get; set; }
        public Nullable<double> AvgSpentTime1 { get; set; }
        public Nullable<double> VarSpentTime1 { get; set; }
        public Nullable<double> speedAvg2 { get; set; }
        public Nullable<double> speedVar2 { get; set; }
        public Nullable<double> AvgSpentTime2 { get; set; }
        public Nullable<double> VarSpentTime2 { get; set; }
        public Nullable<double> speedAvg3 { get; set; }
        public Nullable<double> speedVar3 { get; set; }
        public Nullable<double> AvgSpentTime3 { get; set; }
        public Nullable<double> VarSpentTime3 { get; set; }
        public Nullable<double> speedAvg4 { get; set; }
        public Nullable<double> speedVar4 { get; set; }
        public Nullable<double> AvgSpentTime4 { get; set; }
        public Nullable<double> VarSpentTime4 { get; set; }
        public Nullable<double> speedAvg5 { get; set; }
        public Nullable<double> speedVar5 { get; set; }
        public Nullable<double> AvgSpentTime5 { get; set; }
        public Nullable<double> VarSpentTime5 { get; set; }
        public Nullable<double> speedAvg6 { get; set; }
        public Nullable<double> speedVar6 { get; set; }
        public Nullable<double> AvgSpentTime6 { get; set; }
        public Nullable<double> VarSpentTime6 { get; set; }
        public Nullable<double> MaxSpeed { get; set; }
        public Nullable<double> MinSpeed { get; set; }
        public Nullable<double> SpeedRange { get; set; }
        public Nullable<double> MaxTime { get; set; }
        public Nullable<double> MinTime { get; set; }
        public Nullable<double> TimeRange { get; set; }
        public Nullable<double> TotalTime { get; set; }
        public Nullable<int> anomaly1Id { get; set; }
        public Nullable<int> anomaly2Id { get; set; }
        public Nullable<int> anomaly3Id { get; set; }
        public Nullable<int> anomaly4Id { get; set; }
        public int ContainAnomaly { get; set; }
    }
}
