//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadScanner.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentChain
    {
        public int Id { get; set; }
        public int Segment1Id { get; set; }
        public int Segment2Id { get; set; }
        public int Segment3Id { get; set; }
        public int Segment4Id { get; set; }
        public int Segment5Id { get; set; }
        public int Segment6Id { get; set; }
        public int Segment7Id { get; set; }
        public short PredictedAnomalyType { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
